# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics Template
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    environment: 
      name: Metrics
    
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: markkyn
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo